version: '2'

services:
  app:
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: .
    container_name: app
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/shkaf
      - SPRING_DATASOURCE_USERNAME=ADMIN
      - SPRING_DATASOURCE_PASSWORD=12345
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8090:8090"

  db:
    image: 'postgres:14.5'
    container_name: db
    environment:
      POSTGRES_DB: shkaf
      POSTGRES_USER: ADMIN
      POSTGRES_PASSWORD: 12345
    volumes:
      - pgdata:/docker/db/scripts/library:/docker-entrypoint-initdb.d
    ports:
      - "5500:5432"

volumes:
  pgdata: {}